# This is a basic workflow that is manually triggered

name: Create DFS Languages Update PR

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '0 0 * * 1,2,3,4,5'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_pr"
  create_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Copy the file to lang repo
      run: 
        export GITHUB_USER=dmigliorisi;
        export GITHUB_TOKEN=${{ secrets.IWA_TOKEN }};
        BRANCH_STAMP="$(date +"%Y%m%d%H%M%S")";
        SHORT_DATE="$(date +"%Y-%m-%d")";
        SOURCE_REPO="http://github.com/$GITHUB_USER/fanduel-assignment.git";
        DESTINATION_REPO="https://github.com/fanduel/dfs-languages.git";
        
        git config --global user.email "danny.migliorisi@fanduel.com";
        git config --global user.name "Connector";

        git clone $DESTINATION_REPO destination --depth 1;
        git clone -o upstream $SOURCE_REPO source;
        cd origin
        git remote add origin $SOURCE_REPO;

        git checkout -b $BRANCH_STAMP;

