# This is a basic workflow that is manually triggered

name: Create DFS Languages Update PR

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - master
    paths:
    - 'en_US.json'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_pr"
  create_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Copy the file to lang repo
      run: |
        export GITHUB_USER=dmigliorisi
        export GITHUB_TOKEN=${{ secrets.IWA_TOKEN }}
        
        SHORT_DATE="$(date +"%Y-%m-%d")"
        BRANCH_STAMP="i18n-$(date +"%Y%m%d%H%M%S")"
        
        SOURCE_REPO="http://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/$GITHUB_USER/fanduel-assignment.git"
        DESTINATION_REPO="https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/fanduel/dfs-languages.git"
        
        git config --global user.email "dmigliorisi@gmail.com"
        git config --global user.name "Connector"

        git clone $DESTINATION_REPO destination
        git clone $SOURCE_REPO source

        cd destination
        git checkout -b $BRANCH_STAMP

        cd ..
        cp -f source/en_US.json destination/messages
        cd destination
                
        git add .
        git commit -m "Update language files - $SHORT_DATE" --signoff
        git push --set-upstream origin $BRANCH_STAMP
        gh pr create --title "Language file bump" --body "This is just a test"
