# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create_pr"
  create_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Copy the file to lang repo
      run: 
        export GITHUB_USER=dmigliorisi
        git config --global user.email "danny.migliorisi@fanduel.com"
        git config --global user.name "FD L10n Connector

        git clone https://github.com/FanDuel/dfs-languages.git --depth 1
        git clone -o upstream https://github.com/dmigliorisi/fanduel-assignment
        
        cd fanduel-assignment
        git remote add origin https://github.com/dmigliorisi/fanduel-assignment
        
        
        
